### ISSUE TITLE
Fix issue with table's left margin

### ISSUE THREAD

**Issue by nahuelperafan** [nahuelperafan/Simulador-Estadistico#3]
Table appears cut at the left side:

<img width="1678" alt="Captura de Pantalla 2023-02-14 a la(s) 16 39 56" src="https://user-images.githubusercontent.com/90729306/218841283-a1665ba7-2808-44e5-9b4c-4b00edc573d6.png">

Fix the left side so that it displays as the right side.

**Comment by lucianoarguello335** [comment]
Utilizando CSS Grid se resolvio el problema del layout o disposicion de tanto la tabla como los controles inferiores.
